services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitforce-web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - bitforce-network

  certbot:
    image: certbot/certbot
    container_name: bitforce-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email turl06112002@gmail.com -d bitforce-fund.ru -d www.bitforce-fund.ru --agree-tos
    depends_on:
      - web

networks:
  bitforce-network:
    driver: bridge
