version = 4.2.0
archive_dir = /etc/letsencrypt/archive/bitforce-fund.ru
cert = /etc/letsencrypt/live/bitforce-fund.ru/cert.pem
privkey = /etc/letsencrypt/live/bitforce-fund.ru/privkey.pem
chain = /etc/letsencrypt/live/bitforce-fund.ru/chain.pem
fullchain = /etc/letsencrypt/live/bitforce-fund.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 8f747a9ca0dda515d3fb65f60c8c7bf1
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
bitforce-fund.ru = /var/www/certbot
www.bitforce-fund.ru = /var/www/certbot
